### ISSUE TITLE
Some problem about the details

### ISSUE THREAD

**Issue by Jingwei-Liao** [bb12346/GaitGL#1]
hello，we re-implement your code and we can't reach the performance you show in the paper (example, 86.0 in ST-NM), can you show more detail between feature mapping and loss function which we find the code and paper are different

**Comment by bb12346** [comment]
hi, this code is corresponding to [A], which is used to HID2020 [B].

[A] Learning Effective Representations from Global and Local Features for Cross-View Gait Recognition
[B] http://hid2020.iapr-tc4.org/hid-2020-competition-results/

**Comment by Jingwei-Liao** [comment]
We find the difference between the HID2020 and your ICCV21 paper is the loss function, but your ICCV21 paper doesn't show the detail about the loss function, can you show me more? Thanks very much !

**Comment by bb12346** [comment]
We will release our code (ICCV version) as soon as possible. :)

**Comment by Jingwei-Liao** [comment]
oh, thanks, will the iccv code still release on this account?

**Comment by bb12346** [comment]
I think I can send you the details of the loss function by email. Can you provide me with your email？

**Comment by bb12346** [comment]
> oh, thanks, will the iccv code still release on this account?

Yes.

**Comment by Jingwei-Liao** [comment]
Thinks for your help! This is my email 3222413873@qq.com
