### ISSUE TITLE
使用test_oumvlp报错

### ISSUE THREAD

**Issue by HUAFOR** [bb12346/GaitGL#2]
您好，有个问题不知道能不能冒昧的请教您一下：就是在使用您的代码在测试OUMVLP数据集时出现了以下错误：
想简单问下您有出现过类似的问题吗？
![image](https://user-images.githubusercontent.com/58834906/147872743-da745834-5896-42fe-ad59-440bfd7da01e.png)

**Comment by bb12346** [comment]
这个问题我倒是没遇到过，测试过程应该也是能跑通的...
