### ISSUE TITLE
关于测试模型时候的一些问题

### ISSUE THREAD

**Issue by hxi667** [bb12346/GaitGL#3]
您好，我注意到在test_oumvlp.py代码中，您对模型迭代测试了250k？请问 测试评估的时候为什么需要iter呢？
另外测试使用CASIA-B训练的模型时的iter是多少呢？

**Comment by bb12346** [comment]
您好，设置iter是为了批量测试不同epoch的精度，最后选择了250k。CASIA-B的iter是80k。

**Comment by hxi667** [comment]
在代码中我没有看到epoch这个参数






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "bb12346/GaitGL"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月28日(星期一) 晚上7:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [bb12346/GaitGL] 关于测试模型时候的一些问题 (Issue #3)





 
您好，设置iter是为了批量测试不同epoch的精度，最后选择了250k。CASIA-B的iter是80k。

**Comment by bb12346** [comment]
是我说的不够严谨，就是config.py文件中的'total_iter': 250000

**Comment by hxi667** [comment]
谢谢你的解答~



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年3月28日(星期一) 晚上7:43
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [bb12346/GaitGL] 关于测试模型时候的一些问题 (Issue #3)





 
是我说的不够严谨，就是config.py文件中的'total_iter': 250000
